title = "TOML format config for thermocouple reading to influxDB"

test_name="testing"

[database]
server = "chester.local"
DBName = "TC"
username = "TCCollect"
password = "magic4052"

[[probe]]
num=1
name="room_temp"

[[probe]]
num=2
name="display"

[[probe]]
num=10
name="toohigh"
