title = "TOML format config for thermocouple reading to influxDB"

test_name="testing"

[database]
server = "chester.local"
DBName = "TC"
username = "TCCollect"
password = "magic4052"

[[probe]]
num=1
name="room_temp"

[[probe]]
num=2
name="probe_2"

[[probe]]
num=3
name="probe_3"

[[probe]]
num=4
name="probe_4"

[[probe]]
num=5
name="probe_5"

[[probe]]
num=6
name="probe_6"

[[probe]]
num=7
name="probe_7"

[[probe]]
num=8
name="probe_8"
