title = "TOML format config associated with reading ginlong/Solis solar inverters"
debugLevel = 1

[database]
server = "chester.local"
DBName = "solar"
username = "K6TD"
password = "magic4052"

[IPinfo]
tcpport = "8510"
